version: '2'
services:
    dandy-app:
        image: lfkeitel/dandelion:latest
        depends_on:
            - dandy-db
        environment:
            - DANDELION_DB_HOST=dandy-db
            - DANDELION_DB_USER=root
            - DANDELION_DB_PASSWORD=dandy_dev
        container_name: 'dandy-app'
        ports:
            - "${DANDY_HOST_PORT}:80"
        # volumes:
        #     - .:/app
        #     - ./docker/config.php:/app/app/config/config.php

    dandy-db:
        image: mariadb:latest
        container_name: 'dandy-db'
        environment:
            MYSQL_ROOT_PASSWORD: dandy_dev
            MYSQL_DATABASE: dandelion
        volumes:
            - ./app/install/mysql_schema.sql:/docker-entrypoint-initdb.d/a.sql
            - ./app/install/upgrades/db_upgrade_mysql_6.2.0.sql:/docker-entrypoint-initdb.d/b.sql
