version: '3'
services:
    dandy-app:
        image: lfkeitel/dandelion:6.2.1
        container_name: dandy-app
        depends_on:
            - dandy-db
        environment:
            - DANDELION_DB_HOST=dandy-db
            - DANDELION_DB_USER=root
            - DANDELION_DB_PASSWORD=dandy_dev
            - "DANDELION_HOSTNAME=http://localhost:${DANDY_HOST_PORT}"
            - DANDELION_DEBUG=true
            - DANDELION_PUBLIC_API=true
        ports:
            - "${DANDY_HOST_PORT}:80"
        volumes:
            - .:/var/www/dandelion
            - ./public/dist:/var/www/dandelion/public
            - ./docker/opcache.ini:/etc/php7/conf.d/opcache.ini:ro

    dandy-db:
        image: mariadb:latest
        container_name: dandy-db
        environment:
            MYSQL_ROOT_PASSWORD: dandy_dev
            MYSQL_DATABASE: dandelion
        volumes:
            - ./app/install/mysql_schema.sql:/docker-entrypoint-initdb.d/a.sql:ro
            - ./app/install/upgrades/db_upgrade_mysql_6.2.0.sql:/docker-entrypoint-initdb.d/b.sql:ro
