version: '2'
services:
    dandy-app:
        image: 'bitnami/php-fpm:${DANDY_PHP_VER}'
        container_name: 'dandy-app'
        volumes:
        - .:/app

    dandy-web:
        image: nginx:1.11.8-alpine
        container_name: 'dandy-web'
        depends_on:
        - dandy-app
        links:
        - dandy-app
        volumes:
        - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./public:/app
        ports:
        - "8085:80"
        command: "nginx -g 'daemon off;'"